let mapleader = "\<Space>"
set nocompatible
set t_Co=256

set showcmd
set laststatus=2
set number
set relativenumber
set ruler
set path+=**
set wildmenu
set wildmode=longest:full,full
set ignorecase
set smartcase
set hidden
set splitbelow
set splitright
set nobackup
set nowritebackup
set shortmess+=c
set updatetime=300
set timeoutlen=2000
set virtualedit=all
syntax on
set background=light
colorscheme PaperColor

"""" identation """"
filetype plugin indent on
set autoindent
set shiftwidth=4
set softtabstop=4
set tabstop=4
set expandtab

"""" search """"
"set hlsearch
set incsearch
nnoremap <Leader>w /\s\+$<Enter>
nnoremap <Leader>W :%s/\s\+$//g<Enter>

"""" windows """""
nnoremap <C-h> <C-W>h
nnoremap <C-j> <C-W>j
nnoremap <C-k> <C-W>k
nnoremap <C-l> <C-W>l

"""" cscope """"
set cscoperelative

"""" netrw """"
let g:netrw_browse_split=4
let g:netrw_winsize=20

"""" sneak """"
let g:sneak#label = 1

"""" lightline """"
let g:lightline = {
    \   'colorscheme': 'PaperColor',
    \   'active': {
    \       'left': [ [ 'mode', 'paste' ],
    \                 [ 'gitbranch', 'readonly', 'filename', 'modified' ] ]
    \   },
    \   'inactive': {
    \       'left': [ [ 'gitbranch', 'readonly', 'filename', 'modified' ] ]
    \   },
    \ }


"""" Fkeys """"
map <F1> <Esc>:NERDTreeToggle<Enter>

map <Leader>g :GitGutterBufferToggle<Enter>
map <Leader>G :GitGutterEnable<Enter>

"""" syntax """"
hi cConstant        cterm=NONE ctermfg=Black
hi cIdentifier      cterm=NONE ctermfg=Black
hi cFunction        cterm=NONE ctermfg=Black
hi cStatement       cterm=NONE ctermfg=Black
hi cPreProc         cterm=NONE ctermfg=Black
hi cType	        cterm=NONE ctermfg=Black
hi cSpecial         cterm=NONE ctermfg=Black
hi cDelimiter       cterm=NONE ctermfg=Black
hi cRepeat          cterm=NONE ctermfg=Black
hi cNumber          cterm=NONE ctermfg=Black
hi cStorageClass    cterm=NONE ctermfg=Black
hi cIncluded        cterm=NONE ctermfg=Black
hi cStructure       cterm=NONE ctermfg=Black
hi cConditional     cterm=NONE ctermfg=Black
hi cLabel           cterm=NONE ctermfg=Black
hi cOperator        cterm=NONE ctermfg=Black

source ~/.vim/coc.vim
set tagfunc=CocTagFunc

let g:ctrlp_map = ''
nnoremap <leader>; :CtrlPBuffer<cr>
nnoremap <leader>' :CtrlP<cr>
let g:ctrlp_working_path_mode = ''

if &diff
     function! IwhiteToggle()
       if &diffopt =~ 'iwhite'
         set diffopt-=iwhite
       else
         set diffopt+=iwhite
       endif
     endfunction
     map gs :call IwhiteToggle()<CR>
 endif



set wildignore+=*.o,*.ko,*.o.cmd
let g:ctrlp_working_path_mode = 0
let g:ctrlp_max_files=0
let g:ctrlp_max_depth=40

